### ISSUE TITLE
No highlight for PROC statement after another PROC and inside a THEN clause

### ISSUE THREAD

**Issue by paulossilva** [remy/txt2bas#13]
![Captura de Tela 2020-05-16 às 11 23 33](https://user-images.githubusercontent.com/940695/82122141-2583a980-9768-11ea-85a2-6fcce71d8a88.png)

**Comment by remy** [comment]
Is this online on zx.remysharp.com or in vscode? (Just so I know where to look at the syntax highlighting)

**Comment by paulossilva** [comment]
It's in the online editor (sorry, I didn't make myself clear).
BTW, I've found some issues with the VSCode plugin as well. May I post them here later?

**Comment by paulossilva** [comment]
I've attached another example of this issue. It seems the problem occurs when have more the one parenthesis on the same line 

![Captura de Tela 2020-05-16 às 22 03 12](https://user-images.githubusercontent.com/940695/82133349-94d9b780-97c1-11ea-8d81-1c6f5e4ac6b3.png)

**Comment by remy** [comment]
That's fixed and live - thank you.

<img width="892" alt="Screenshot 2020-05-17 at 10 48 19" src="https://user-images.githubusercontent.com/13700/82141164-f20a5300-982b-11ea-8bd9-277210d302f3.png">
