### ISSUE TITLE
Lines started with semicolon or hash sign don't appear as comment

### ISSUE THREAD

**Issue by paulossilva** [remy/txt2bas#15]
On the online editor, lines started with ; or # should be treated as comments and coloured green.

**Comment by remy** [comment]
They are, what do you see?
![Screenshot_20200517-095409](https://user-images.githubusercontent.com/13700/82140015-68a35280-9824-11ea-9a92-4dcb5f441bdb.png)

**Comment by remy** [comment]
(excuse the massive screenshot 😆 )

**Comment by paulossilva** [comment]
I should have been more clear, sorry! I don't use line numbers in my NextBasic code since we have the #autoline directive, which is very helpful. So, without line numbers, comment lines aren't displayed as such in the online editor. As you haven't implemented the autoline directive (yet), please consider this issue as a feature request instead of a bug. Thanks!

![Captura de Tela 2020-05-17 às 11 23 27](https://user-images.githubusercontent.com/940695/82151413-03eef480-9832-11ea-94ae-fb91bbbc7093.png)

**Comment by remy** [comment]
Ah, I suspect you're not actually writing NextBASIC but using some extra layer of interpretation (maybe Boriel's ZX Basic?).

I just tried the following lines in NextBASIC both in the editor itself on the Next and in a text file and converting with .txt2bas on the Next, and they both error:

```
#autoline

PRINT "Hello world"
; this is a comment
```

<img width="753" alt="Screenshot 2020-05-17 at 16 11 34" src="https://user-images.githubusercontent.com/13700/82152446-1b8da380-9859-11ea-99a6-2fbfa0308c24.png">

_Edit: 2nd screenshot was supposed to be of .txt2bas but failed!_

I'm not sure I plan to support outside of NextBASIC but it might be useful to get an idea of what you're actually doing (rather than me guessing as zxbasic)

**Comment by paulossilva** [comment]
No, I'm just using plain NextBasic. The #autoline directive is supported by the .txt2bas dot command bundled with the Next distribution. Try .txt2bas -h in the command line. This directive is not supported on the NextBasic editor by the way.

![IMG_9406](https://user-images.githubusercontent.com/940695/82152750-d017cd00-9839-11ea-917b-0159d525d0f9.JPG)

![IMG_9407](https://user-images.githubusercontent.com/940695/82152766-e58cf700-9839-11ea-957c-d1e2a34028df.JPG)

**Comment by paulossilva** [comment]
This directive is very helpful because, combined with procedures, it allows us to write NextBasic programs without the hassle of keeping track of line numbers (no need for GOTOs nor GOSUBs anymore). Check the NextInvaders game demo bundled with the latest distro, to have a glimpse of what I'm talking about.

**Comment by remy** [comment]
Oh wow, yeah - I see it in Nextinvaders now (and I had that in my test fixtures but hadn't spotted it at all!).

Right… I'll get that sorted. TIL ;-)

**Comment by remy** [comment]
Note for self: `autoline` seems to be a `.txt2bas` feature, the [basicinvaders](https://gitlab.com/thesmog358/tbblue/-/blob/master/games/Next/NextBASIC%20Invaders/basicInvaders.bas) contains line numbers on each statement - checked with [unpack](https://unpack.isthe.link/) + this unpacker:

```
<A8$sig
C$marker
C$issue
C$version
I$length
C$hType
S$hFileLength
S$autostart
S$hOffset
x
x104
C$checksum
n$lineNumber
s$len
A34
```

Specifically `n$lineNumber` is `10` (and peeking forward I see `20`).

**Comment by remy** [comment]
This is also landing in zx.remysharp.com/bas now - thanks for the report (I picked this for my evening hack)
