### ISSUE TITLE
VSCode NextBasic export command doesn't support the #program directive

### ISSUE THREAD

**Issue by paulossilva** [remy/txt2bas#17]
The #program directive is supported by the txt2bas dot command and defines the name for the .bas output file.

When exporting a text NextBasic program to the .BAS format, the name defined in this directive (when present) should be used to automatically save the resulting file. The VSCode save dialog should use it as the default file name (instead of suggesting 'no title').

**Comment by remy** [comment]
Good shout 👌

**Comment by remy** [comment]
Going into the vscode extension 1.3.3 (in some early morning coding!)
