### ISSUE TITLE
VSCode NextBasic plugin doesn't complete PROC names

### ISSUE THREAD

**Issue by paulossilva** [remy/txt2bas#18]
After typing PROC and the initial letters of its name, the plugin correctly suggests the name of a given procedure, but when pressing enter (when the list is down to one item) or choosing a name from the list, it simply creates a new line without completing the procedure name.

**Comment by remy** [comment]
Just making a note, but I'm not sure this is my extension at play, as I've not added any autocomplete. I suspect vscode is offering the autocomplete and either the selection key is [tab] *or* my `enter` shortcut is messing with things. 

I'll give it a test later today and confirm what's happening.

**Comment by remy** [comment]
Just tested, I'm pretty certain that if you want to use autocomplete in vscode it should be tab to select - it's certainly what I've been doing.

**Comment by paulossilva** [comment]
You're right! Don't know how I couldn't figure that out! Sorry
