### ISSUE TITLE
.BAS file won't load into TXT2BAS pane?

### ISSUE THREAD

**Issue by StreeterN** [remy/txt2bas#27]
I have tried to load this into the converter to convert from .BAS to .TXT all my other files work OK, This one just leaves the drag and drop panel blank. I have saved as .BAS clean, and can't see anything that might cause this. Not urgent as I can convert from .command line. Attached offending file.

[colorpick.zip](https://github.com/remy/txt2bas/files/5416518/colorpick.zip)

**Comment by remy** [comment]
Cheers. I'll take a look and find out what's going on.

**Comment by remy** [comment]
Thank you - that's fix and going live right now.

**Comment by StreeterN** [comment]
Brilliant, I have converted several others since so seems unique to that one.

Best regards

Neil

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
