### ISSUE TITLE
.tap extension doesn't build as TAP file

### ISSUE THREAD

**Issue by MartinMSPedersen** [remy/txt2bas#28]
I have a text-file with one long line like this:

`10 DATA 61,1773,1839,1551,1781,1276,1372,1668,1823,1870,1672,1821,1327,1902,1949,1389,1720,1437,1716,1360,1893,1410,1881,1927,1639,1514,1753,1625,1249,1696,1698,1699,2004,1742,1903,473,1948,1830,1973,2005,1468,1824,1809,1493,2009,1848,1306,1519,1618,1905,1402,1705,1910,1609,1571,1557,1420,608,1471,1383,1442`

`txt2bas -i input.txt -o output.tap` runs without producing any errors or warnings.
However output.tap doesn't load because it is broken.
> fuse: error: libspectrum: libspectrum_tap_read: not enough data in buffer

**Comment by MartinMSPedersen** [comment]
Oh. It worked when I supplied an extra flag:
`-f tap`

**Comment by MartinMSPedersen** [comment]
So it guess the error is that even if the output-filename ends with .tap then it is still trdos format.

**Comment by remy** [comment]
Good catch - I'll update this to handle the case where the output filename ends in .tap to auto switch to TAP format 👍
