### ISSUE TITLE
Decoding .bas files fails with "TextDecoder underfined"

### ISSUE THREAD

**Issue by ewe2** [remy/txt2bas#30]
I'm running it on a Debian bullsye box.

Installed with `npm -global txt2bas` and I tested it on Alex Aris' UP code:
```
Script started on 2021-04-26 10:00:05+10:00
ewe2@marvin:~/devel/zx-spectrum-next/up/ZX Spectrum Next/V1.0$ bas2txt -i UP.bas
TextDecoder is not defined
ewe2@marvin:~/devel/zx-spectrum-next/up/ZX Spectrum Next/V1.0$ exit
exit
Script done on 2021-04-26 10:00:16+10:00
```

you can find his file at [https://gitlab.com/alexarisgames/up/-/tree/master/ZX%20Spectrum%20Next/V1.0](https://gitlab.com/alexarisgames/up/-/tree/master/ZX%20Spectrum%20Next/V1.0)

Let me know if there's any other testing I can do, very keen to have a workable decoder for the files outside of an emulator or the computer itself (when it turns up here in a few months!).

**Comment by remy** [comment]
What version of node are you running? I suspect an old version is the problem here.

**Comment by ewe2** [comment]
I appear to be running v12.21.0. Also I tried to use your web url with the following result:

```
ewe2@marvin:~/devel/zx-spectrum-next/up/ZX Spectrum Next/V1.0$ curl https://zx.remysharp.com/bas2txt -F 'file=@./UP.bas'
Redirecting to https://txt2bas.vercel.app/api/bas2txt (308)
```
So no luck there either.

**Comment by remy** [comment]
Hmm, TextEncoder should be there in node 12...

I'm without broadband today, but I'll try to get a test script up for you.
The npm installed version should work out of the box (I'm on 12 myself).

I'll have to look at why the web service is failing too - likely it was
forgotten about as the local version has been stable for a while.

**Comment by remy** [comment]
2 years later - I can say the curl method works, I tried it with your file (sorry for huuuuuge delay!).
