### ISSUE TITLE
Drag Drop Online Conversion of TestCard.TXT not saving anything

### ISSUE THREAD

**Issue by Luzie67** [remy/txt2bas#33]
Hi,

I drag and drop attached TestCard.txt-File to Online-Converter at: https://zx.remysharp.com/bas/
[TestCard.txt](https://github.com/remy/txt2bas/files/7086272/TestCard.txt)
Then I try to download in .TAP or (+3 DOS) .BAS-Format. It asks for a filename, but than nothing more happens / no saving happen. What am I doing wrong?

**Comment by Luzie67** [comment]
...tried with .txt2bas under CSpect-Emulator. This converts without error, but while running testcard,bas it won´t run correct and show special characters. So I think the Slashes etc. maybe the problem for conversion?
Git the original from here: https://www.facebook.com/groups/232541547272192/user/100003197802119/
as:
(on Facebook it´s with proper Line Break instead of here on this Github-Window. But has proper Line Break in testcard.txt):
Paste this in Basinc and replace underscore characters with spaces.

```
1 GO SUB 900
10 INK 7: PAPER 0: BORDER 0: CLS
20 LET s=2
30 FOR c=0 TO 20 STEP 2: GO SUB 300: NEXT c
40 LET s=1: LET c=0: GO SUB 300
60 FOR c=3 TO 6: PRINT AT c,5;"\{p7}___\{p6}___\{p5}___\{p4}___\{p3}___\{p2}___\{p1}___\{p0}___": NEXT c
70 FOR c=7 TO 10: PRINT AT c,5;"____\i\i\i\i\i\k\k\k\k\k\::\::\::\::\::\{b1}\::\::\::\::\::\{b0}": NEXT c
80 PRINT AT 11,5;"\{b1}\::\::\::\::_______________\::\::\::\::\::\{b0}": PRINT AT 12,5;"\{b1}\::\::\::\::__ZX SPECTRUM__\::\::\::\::\::\{b0}"
90 FOR c=13 TO 14: PRINT AT c,5;"\{b1}\::\::\::\{b0}";TAB 21; PAPER 6; INK 2;"\j\j\j\j\j\j\j"; PAPER 0;" ": NEXT c
92 FOR x=0 TO 20 STEP 5: PLOT 70+x,56: DRAW 0,15: NEXT x
94 FOR x=0 TO 28 STEP 3: PLOT 100+x,56: DRAW 0,15: NEXT x
96 FOR x=0 TO 20 STEP 2: PLOT 142+x,56: DRAW 0,15: NEXT x
100 FOR c=15 TO 16: PRINT PAPER 7; BRIGHT 1;AT c,5;TAB 29: NEXT c
110 FOR c=17 TO 20: PRINT BRIGHT 1;AT c,5;"\{p7} \{p6} \{p5} \{p4} \{p3} \{p2} \{p1} \{p0} ": NEXT c
140 PLOT 136,119: DRAW PAPER 8;0,-63
142 PLOT 40,88: DRAW 191,0
143 PLOT 40,88: DRAW 0,31
150 PLOT 90,0: DRAW 92,0,-5.24
299 PAUSE 0: GO TO 1e4
300 PRINT #s;AT c,0;
303 PRINT #s;"\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d\f\d"
305 PRINT #s;" \e \e \e \e \e \e \e \e \e \e \e \e \e \e \e \e"
330 RETURN
900 RESTORE 901: FOR F=65368 TO 65535: READ A: POKE F,A: NEXT F: RETURN
901 DATA 255,128,128,128,128,128,128,128
902 DATA 255,0,0,0,0,0,0,0
903 DATA 255,1,1,1,1,1,1,1
904 DATA 128,128,128,128,128,128,128,255
905 DATA 128,128,128,128,128,128,128,128
906 DATA 0,0,0,0,0,0,0,255
907 DATA 1,1,1,1,1,1,1,255
908 DATA 1,1,1,1,1,1,1,1
909 DATA 136,34,168,70,144,34,137,50
910 DATA 170,85,170,85,170,85,170,85
911 DATA 170,247,89,111,186,247,85,191
912 DATA 0,64,64,64,64,64,126,0
913 DATA 0,66,102,90,66,66,66,0
914 DATA 0,66,98,82,74,70,66,0
915 DATA 0,60,66,66,66,66,60,0
916 DATA 0,124,66,66,124,64,64,0
917 DATA 0,60,66,66,82,74,60,0
918 DATA 0,124,66,66,124,68,66,0
919 DATA 0,60,64,60,2,66,60,0
920 DATA 0,254,16,16,16,16,16,0
921 DATA 0,66,66,66,66,66,60,0
```

**Comment by remy** [comment]
Cheers. I'm about to have a short holiday (mostly away from computers), but when I'm back next week I'll look into it and fix - sounds like a parsing error on my side somewhere. Cheers 👍

**Comment by Luzie67** [comment]
Dear Remy,
I I think we can close this Issue as I tried today what the author of the Basic program says ="Paste this in Basinc and replace underscore characters with spaces." and this works (no Next is necessary, this runs on a 48k as well).
