### ISSUE TITLE
Saving NextBasic program in TXT-Format saves error in +3DOS .BAS-Format

### ISSUE THREAD

**Issue by Luzie67** [remy/txt2bas#36]
Hi,

while pasting this NextBASIC-Text from: https://forum.tlienhard.com/phpBB3/viewtopic.php?p=53313#p53313
and saving it to +3DOS .BAS-Format with https://zx.remysharp.com/bas/
the line 5020 won´t be converted/saved correctly:
On .BAS-File I get:
c::\\demos\\.extBASIC\\basicSprites\\dksprite.spr
instead of:
c::\\demos\\NextBASIC\\basicSprites\\dksprite.spr

btw., When I change the original Text to lower case "n": c::\\demos\\NextBASIC\\basicSprites\\dksprite.spr
this is save OK.

**Comment by remy** [comment]
Long overdue reply (I mean, we're nearly 2 years late!) - but closing with an answer in case anyone else comes along.

The `\\N` in (my) txt2bas is actually a map to UDG N (which I'd imagine is empty initially). This is why the text is being corrupted.

However, the way the file system - in the example code - is being referenced is wrong. It should be:

```
5020 LOAD "c:/demos/NextBASIC/basicSprites/dksprite.spr" BANK %m
```

This is both consistent with the manual/docs but also avoids the pitfall of the UDG character that I'm trying to support.
