### ISSUE TITLE
Split .txt into multiple .bnk files

### ISSUE THREAD

**Issue by NealeTools** [remy/txt2bas#39]
Hi Remy, I posted on FaceBook and Messenger too as wasn't sure where best to contact you.

My suggestion is to utilise the syntax of the directives within Garry's native txt2bas on the Next (see screen grab) which allow a txt file to be converted either to .bas (with a +3DOS header) or to a bank (without a header I presume).

To do this, within the main .txt file, a coder would simply include the directive:
#bankfile BANKNAME
in front of any relevant code lines.

Then, on build and run (Command+R), the main .txt file would be split and and everything up to the #bankfile line would be converted to the normal .bas file that autoruns, and anything that follows #bankfile (up to the next "#bankfile" directive, if there is one) would get pushed to the file "BANKNAME.bnk".

Ideally, a single .txt could then have multiple #bankfile directives so that the single .txt file can get converted into one .bas and multiple .bank files.

Currently I have to manage 10+ .txt files separately—and convert one to .bas (the main program), and the others to .bnk (the helper/extension files), which gets really cumbersome and tedious, and will only get more challenging as projects increase in size.

I hope this makes sense. As far as I can tell, you .txt2bas converter can make both .bas and .bnk output files, so the only part missing is a way to split the .txt file at each #bankfile directive and to read the BANKNAME after each one so that the .bnk files are named correctly as BANKFILE.bnk

Many thanks for your interest and support on this tool!

<img width="546" alt="image" src="https://github.com/remy/txt2bas/assets/19664927/2c5227db-934a-4423-9c5a-f7960028b140">

**Comment by remy** [comment]
going live in the next vscode release
