### ISSUE TITLE
8x8 sprites colour palette isnt wsorking

### ISSUE THREAD

**Issue by speccynut** [remy/txt2bas#45]
Hi Remy,

This was flagged by Ricardo in the next basic fb group.
When you select 8x8 tiles in the tile map mode (or click the toggle 8x8 mode on sprite page) the palette locks you down to a limited range of colours and not the full palette.

It used to work - Matt Davies wrote orb run in nexxt basic and as part of the game uses a set of 8x8 tiles to generate a font.  There are several examples of this in the orb folder on the ks1 distro.

Not sure whats changed.  next basic doesnt support 8x8 sprites however it should support them for tiles which it can support.

Adrian

**Comment by remy** [comment]
Sod, it's wrongly forcing you into a 4bit tile set. I'll fix that.

**Comment by speccynut** [comment]
awesome!   Thanks Remy!
