### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by HeartWareDK** [remy/txt2bas#8]
Sending this HTTP request:

POST /txt2bas HTTP/1.1
Host: zx.remysharp.com
Accept: */*
Content-Type: text/plain
Content-Length: 13

text=10 PRINT

(I have tried it both with and without the text= lead-in)

results in error 500 Internal Server Error

**Comment by remy** [comment]
Yeah, perfect. It's a bad content-type that's being sent.

For a quick test, try with this `Content-Type: application/x-www-form-urlencoded` (it's the right type for posted content), but I'll see if I can add some simpler handling for missing and wrong-ish content types.

**Comment by remy** [comment]
Oh weird. I was able to replicate your bug with reqbin.com - then I sent another request and it worked.

I wonder if there's something up with the hosted function, could be tricky to debug!

**Comment by HeartWareDK** [comment]
It would be much, much easier if you could officially support the text/plain paradigm (without the text=). That's so much easier to program from high-level language :-)

**Comment by HeartWareDK** [comment]
If I send this:

POST /txt2bas HTTP/1.1
Host: zx.remysharp.com
Accept: */*
Content-Type: application/x-www-form-urlencoded
Content-Length: 33

text=10%20PRINT&20%20LET%20A=20&=

I get this back:

HTTP/1.1 500 Internal Server Error
Cache-Control: s-maxage=0
Content-Length: 56
Content-Type: application/json; charset=utf-8
Date: Sun, 03 May 2020 15:18:03 GMT
Etag: W/"38-lN7wNoXFdktiM0qu2JZkE6rymYg"
Server: Netlify
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Now-Id: iad1::sfo1::499g9-1588519083944-dc2645bef67d
X-Now-Trace: iad1
X-Vercel-Id: iad1::sfo1::499g9-1588519083944-dc2645bef67d
Age: 2
Connection: keep-alive
X-NF-Request-ID: 5d1ea858-0744-4a50-b1b5-c861c66b5b3a-7898857

{"error":"Cannot read property 'toString' of undefined"}

**Comment by remy** [comment]
@HeartWareDK I was initially mistaken, I do support completely plain text: https://github.com/remy/zx-tools/blob/master/functions/api/txt2bas.js#L30-L31 - there's something else at play here. It's not actually reading _anything_ from the posted data (believe).

From reqbin.com when I use their curl tool, I can consistently get the 500, but their gui interface, I get it once but not again (unless there's a "bit of time" between requests).

I'm investigating atm.

**Comment by remy** [comment]
I actually think it might be the reqbin tool that's at fault here. I could see multiple content types being sent.

It was working as I'd expect using curl on the commnad line, but I've found an alternative: https://www.apirequest.io/5eaee414e9859c4d90653cc8?at=eyJhcHAiOiI1ZWFlZTQxNGU5ODU5YzRkOTA2NTNjYzgiLCJhdWQiOiI2dVowbk9qZnJyOE5JajRyOEk2Tk51clN2RjdWWTJtTCIsInZlciI6IjEiLCJvcmciOiIwOjAiLCJwZXJtaXNzaW9ucyI6eyIwOjAiOnsic2NwIjoiY3JlYXRlOndvcmtzcGFjZXMgcmVhZDp3b3Jrc3BhY2VzIHVwZGF0ZTp3b3Jrc3BhY2VzIGRlbGV0ZTp3b3Jrc3BhY2VzIn19LCJleHAiOjE1OTEwNTYwMDAsImp0aSI6IjAzNTczZGY5LWUzMDQtNDVhNy05Y2E3LWQ3NjdjYTlhYzAwMSJ9.6RoVBNnmsTPn6Ob5VnL5RQj6HEtTXEl-8Y7uM5sUPfs (this only populates the result rather than the source, but it does get the result I'd expect).

**Comment by HeartWareDK** [comment]
I can't get it to work, neither from my program nor from apirequest.io ...

**Comment by remy** [comment]
Give it another go now. I've added some hack around trying to parse a bare body.

Really the content should be encoded so it can be decoded on the recieving end - so I'm a bit wary the fix might be a bit kludgish.

**Comment by HeartWareDK** [comment]
There's no 8-bit characters included, so encoding shouldn't be necessary (yet).

But I'm still getting 500 ISE when I try a text/plain body...

**Comment by remy** [comment]
Same body? Or different?

**Comment by remy** [comment]
The posted content also supports JSON as `{ "text": "<your NextBASIC>" }` - this might also ensure things like new lines are sent properly

**Comment by HeartWareDK** [comment]
I'm currently investigating while making dinner. It may be my BASIC program that contains something your parser doesn't like, as when I try a simple 10 PRINT program it now works. I'm attempting to narrow it down to the offending line(s)...

**Comment by HeartWareDK** [comment]
Okay - this simple BASIC line crashes your parser:

03-05-2020 19:40:22 POST /txt2bas HTTP/1.0
03-05-2020 19:40:22 Content-Type: text/plain; charset=ISO-8859-1
03-05-2020 19:40:22 Content-Length: 14
03-05-2020 19:40:22 Host: zx.remysharp.com
03-05-2020 19:40:22 Accept: */*
03-05-2020 19:40:22 User-Agent: Mozilla/3.0 (compatible; Indy Library)
03-05-2020 19:40:22 
03-05-2020 19:40:22 5210 PRINT 'P,

Response:
Access-Control-Allow-Origin: *
Cache-Control: s-maxage=0
Content-Length: 49
Content-Type: application/json; charset=utf-8
Date: Sun, 03 May 2020 17:40:17 GMT
Etag: W/"31-XC1CmiH0y1egxtnDNrye+18uNYA"
Server: Netlify
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
X-Now-Id: zrh1::sfo1::t6t92-1588527617843-a5a322872069
X-Now-Trace: zrh1
X-Vercel-Id: zrh1::sfo1::t6t92-1588527617843-a5a322872069
Age: 2
X-NF-Request-ID: a168af15-dd9b-4b19-b317-4895dddac93a-11045605


HTTP/1.0 500 Internal Server Error

**Comment by remy** [comment]
My refactor of the txt2bas is also going to _start_ to include a validator (so errors should trickle down to these post requests).

Feel free to share (or privately) the basic and I can see if there's any validation I can add (in your own time too - I've got kids to put to bed now anyway 😊)

**Comment by HeartWareDK** [comment]
Also in your online version. It's the apostrophe that causes it. It I remove it, it works (in the online version).

In case you don't know, an apostrophe in a PRINT statement is a shortcut for CR/LF and is thus a perfectly legal character, and is not the start of a string...

**Comment by HeartWareDK** [comment]
I've now sent each line of my program separately to your endpoint and all except the following three ones passed:

5210 PRINT 'P,
5260 IF LEN D$>2 OR NOT x THEN PRINT 'D,:ELSE PRINT ',
6050 PRINT #1;AT 0,0;"Adjust bet with Up/Down"'"Press FIRE to play/FIRE2 to stop";

As you can see, in all three cases, there an apostrophe inside a PRINT statement, so it seems like this is the only (fatal) error in your parser (from my limited test).

**Comment by remy** [comment]
Ah, so something like this?

```
10 PRINT "Hello'World"
```

?

**Comment by HeartWareDK** [comment]
No - not within a string. Outside a string. The apostrophe is like the comma - an instruction to PRINT, but whereas the comma means "print enough spaces to move cursor to next tab stop (column 16 or 0)", the apostrophe means "jump to start of next line (without printing anything)"

**Comment by HeartWareDK** [comment]
An apostrophe inside a string just prints an apostrophe, whereas outside a string (in a PRINT statement) it is a shorthand for ";CHR$ 13;CHR$ 10;"

**Comment by HeartWareDK** [comment]
If I fix those three lines to their equivalent:

5210 PRINT : PRINT P,
5260 PRINT : IF LEN D$>2 OR NOT X THEN PRINT D,:ELSE PRINT ,
6050 PRINT #1;AT 0,0;"Adjust bet with Up/Down","Press FIRE to play/FIRE2 to stop";

your parser succeeds (ie. does not fail). Now to see if NextBASIC interpreter can understand your output :-)

**Comment by remy** [comment]
If you find there's any problems (that you want to report), the best thing for me to see is the original source NextBASIC line - then I can convert that using my code, and then again with the Next's .txt2bas and compare the differences to find where (if) I've gone wrong. The places I've seen that my code (previously) got it wrong was around int expressions.

**Comment by HeartWareDK** [comment]
The only one I have found is the PRINT one with the apostrophe.

**Comment by remy** [comment]
Well that was super useful to me. I've was able to confirm the bug, write tests to confirm it and push a fix for that too (in fact it was fixed in my rewrite which was a good sign)

**Comment by remy** [comment]
I'm going to close this issue - I assume all is well now. Happy to reopen or create a new issue if you spot anything or have feedback 👍
